# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.29.0
#   sqlc-gen-better-python v0.4.4
from __future__ import annotations

__all__: collections.abc.Sequence[str] = (
    "MlbPlayer",
    "MlbPlayerGameStat",
    "MlbTeam",
    "NbaDailyBet",
    "NbaPlayer",
    "NbaPlayerGameStat",
    "NbaPlayerSeasonStat",
    "NbaSeason",
    "NbaTeam",
    "NflDailyBet",
    "V2MlbDailyBet",
    "V2NbaDailyBet",
    "V2NflDailyBet",
    "V3NflGame",
    "V3NflGameStat",
    "V3NflPlayer",
    "V3NflTeam",
    "WnbaPlayer",
    "WnbaPlayerGameStat",
    "WnbaPlayerSeasonStat",
    "WnbaSeason",
    "WnbaTeam",
)

import msgspec
import typing

if typing.TYPE_CHECKING:
    import collections.abc
    import datetime
    import decimal


class MlbPlayer(msgspec.Struct):
    id: int
    player_id: int
    long_name: str
    team_abv: str
    pos: str
    height: str
    weight: int
    bat: str | None
    throw: str | None
    b_day: datetime.date | None
    mlb_headshot: str | None
    espn_headshot: str | None
    espn_status: str | None
    injury_description: str | None
    injury_return: str | None


class MlbPlayerGameStat(msgspec.Struct):
    player_id: int
    game_id: str
    team: str | None
    started: bool | None
    starting_position: str | None
    all_positions_played: str | None
    bb: int | None
    ab: int | None
    h: int | None
    hr: int | None
    rbi: int | None
    so: int | None
    avg: float | None
    tb: int | None
    doubles: int | None
    triples: int | None
    r: int | None
    ibb: int | None
    sf: int | None
    sac: int | None
    hbp: int | None
    gidp: int | None
    p_bb: int | None
    p_h: int | None
    p_hr: int | None
    p_er: int | None
    p_so: int | None
    win: str | None
    loss: str | None
    save: str | None
    era: float | None
    innings_pitched: float | None
    fielding_e: int | None
    passed_ball: int | None
    of_assists: int | None
    pickoffs: int | None
    sb: int | None
    cs: int | None
    po: int | None


class MlbTeam(msgspec.Struct):
    team_abv: str
    team_city: str | None
    team_name: str
    conference: str
    division: str
    rs: int
    ra: int
    wins: int
    losses: int
    run_diff: int


class NbaDailyBet(msgspec.Struct):
    id: int
    player_id: str
    team_id: str
    opponent_id: str
    stat_type: str
    line: float
    bet_grade: str
    created_at: datetime.datetime


class NbaPlayer(msgspec.Struct):
    id: int
    name: str
    position: str | None
    team_id: int
    player_pic: str | None
    player_id: int
    injury: str | None


class NbaPlayerGameStat(msgspec.Struct):
    id: int
    player_id: int
    game_id: str
    team_id: int
    minutes_played: decimal.Decimal | None
    points: int | None
    rebounds: int | None
    assists: int | None
    steals: int | None
    blocks: int | None
    turnovers: int | None
    offensive_rebounds: int | None
    defensive_rebounds: int | None
    free_throw_percentage: decimal.Decimal | None
    plus_minus: decimal.Decimal | None
    technical_fouls: int | None
    field_goal_attempts: int | None
    three_point_fg_percentage: decimal.Decimal | None
    field_goals_made: int | None
    field_goal_percentage: decimal.Decimal | None
    three_point_fg_made: int | None
    free_throw_attempts: int | None
    three_point_fg_attempts: int | None
    personal_fouls: int | None
    free_throws_made: int | None
    fantasy_points: decimal.Decimal | None
    home_away: str | None
    opponent: str | None
    game_date: datetime.date | None
    team_abv: str | None


class NbaPlayerSeasonStat(msgspec.Struct):
    id: int
    player_id: int | None
    season_id: int | None
    games_played: int | None
    points_per_game: decimal.Decimal | None
    rebounds_per_game: decimal.Decimal | None
    assists_per_game: decimal.Decimal | None
    steals_per_game: decimal.Decimal | None
    blocks_per_game: decimal.Decimal | None
    turnovers_per_game: decimal.Decimal | None
    field_goal_percentage: decimal.Decimal | None
    three_point_percentage: decimal.Decimal | None
    free_throw_percentage: decimal.Decimal | None
    minutes_per_game: decimal.Decimal | None
    offensive_rebounds_per_game: decimal.Decimal | None
    defensive_rebounds_per_game: decimal.Decimal | None
    field_goals_made_per_game: decimal.Decimal | None
    field_goals_attempted_per_game: decimal.Decimal | None
    three_pointers_made_per_game: decimal.Decimal | None
    three_pointers_attempted_per_game: decimal.Decimal | None
    free_throws_made_per_game: decimal.Decimal | None
    free_throws_attempted_per_game: decimal.Decimal | None


class NbaSeason(msgspec.Struct):
    id: int
    season_year: str


class NbaTeam(msgspec.Struct):
    id: int
    name: str
    team_city: str
    team_abv: str
    conference: str
    ppg: float | None
    oppg: float | None
    wins: int | None
    loss: int | None
    division: str | None
    team_bpg: float | None
    team_spg: float | None
    team_apg: float | None
    team_fga: float | None
    team_fgm: float | None
    team_fta: float | None
    team_tov: float | None
    pace: float | None
    def_rtg: float | None


class NflDailyBet(msgspec.Struct):
    id: int
    player_id: str
    team_code: str
    stat: str
    line: decimal.Decimal
    opponent: str
    bet_grade: str
    created_at: datetime.datetime | None
    price: float | None


class V2MlbDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float
    game_time: datetime.datetime
    game_tag: str


class V2NbaDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime
    price: float | None
    game_time: datetime.datetime | None
    game_tag: str | None


class V2NflDailyBet(msgspec.Struct):
    id: int
    analysis: str
    created_at: datetime.datetime | None
    price: float | None
    game_time: datetime.datetime | None
    game_tag: str | None


class V3NflGame(msgspec.Struct):
    id: int
    home_id: int
    away_id: int
    date: datetime.date


class V3NflGameStat(msgspec.Struct):
    id: int
    game_id: int
    player_id: int
    tfl: decimal.Decimal
    def_td: decimal.Decimal
    sacks: decimal.Decimal
    qb_hits: decimal.Decimal
    fumbles: decimal.Decimal
    fumbles_lost: decimal.Decimal
    solo_tackles: decimal.Decimal
    total_tackles: decimal.Decimal
    forced_fumbles: decimal.Decimal
    pass_deflections: decimal.Decimal
    fumbles_recovered: decimal.Decimal
    defensive_interceptions: decimal.Decimal
    int: decimal.Decimal
    qbr: decimal.Decimal
    rtg: decimal.Decimal
    pass_td: decimal.Decimal
    sacked: str | None
    pass_avg: decimal.Decimal
    pass_yds: decimal.Decimal
    pass_attempts: decimal.Decimal
    pass_completions: decimal.Decimal
    rush_td: decimal.Decimal
    carries: decimal.Decimal
    rush_avg: decimal.Decimal
    rush_yds: decimal.Decimal
    long_rush: decimal.Decimal
    rec_td: decimal.Decimal
    rec_avg: decimal.Decimal
    rec_yds: decimal.Decimal
    long_rec: decimal.Decimal
    targets: decimal.Decimal
    receptions: decimal.Decimal
    kick_returns: decimal.Decimal
    kick_return_td: decimal.Decimal
    kick_return_avg: decimal.Decimal
    kick_return_yds: decimal.Decimal
    kick_return_long: decimal.Decimal
    kick_fg: decimal.Decimal
    kick_points: decimal.Decimal
    kick_extra_points: decimal.Decimal


class V3NflPlayer(msgspec.Struct):
    id: int
    team_id: int
    name: str
    height: str
    position: str
    injuries: str | None


class V3NflTeam(msgspec.Struct):
    id: int
    name: str
    team_code: str
    wins: int
    losses: int
    ties: int
    points_for: int
    points_against: int
    total_tackles: int
    fumbles_lost: int
    defensive_touchdowns: int
    fumbles_recovered: int
    solo_tackles: int
    defensive_interceptions: int
    qb_hits: int
    tackles_for_loss: int
    pass_deflections: int
    sacks: int
    fumbles: int
    passing_td_allowed: int
    passing_yards_allowed: int
    rushing_yards_allowed: int
    rushing_td_allowed: int | None


class WnbaPlayer(msgspec.Struct):
    id: int
    name: str
    position: str
    team_id: int
    player_pic: str | None
    player_id: int
    injury: str | None


class WnbaPlayerGameStat(msgspec.Struct):
    id: int
    player_id: int
    game_id: str
    team_id: int
    minutes_played: decimal.Decimal
    points: int
    rebounds: int
    assists: int
    steals: int
    blocks: int
    turnovers: int
    offensive_rebounds: int
    defensive_rebounds: int
    free_throw_percentage: decimal.Decimal
    plus_minus: decimal.Decimal
    technical_fouls: int
    field_goal_attempts: int
    three_point_fg_percentage: decimal.Decimal
    field_goals_made: int
    field_goal_percentage: decimal.Decimal
    three_point_fg_made: int
    free_throw_attempts: int
    three_point_fg_attempts: int
    personal_fouls: int
    free_throws_made: int
    fantasy_points: decimal.Decimal
    home_away: str
    opponent: str
    game_date: datetime.date
    team_abv: str


class WnbaPlayerSeasonStat(msgspec.Struct):
    id: int
    player_id: int
    season_id: int
    games_played: int
    points_per_game: decimal.Decimal
    rebounds_per_game: decimal.Decimal
    assists_per_game: decimal.Decimal
    steals_per_game: decimal.Decimal
    blocks_per_game: decimal.Decimal
    turnovers_per_game: decimal.Decimal
    field_goal_percentage: decimal.Decimal
    three_point_percentage: decimal.Decimal
    free_throw_percentage: decimal.Decimal
    minutes_per_game: decimal.Decimal
    offensive_rebounds_per_game: decimal.Decimal
    defensive_rebounds_per_game: decimal.Decimal
    field_goals_made_per_game: decimal.Decimal
    field_goals_attempted_per_game: decimal.Decimal
    three_pointers_made_per_game: decimal.Decimal
    three_pointers_attempted_per_game: decimal.Decimal
    free_throws_made_per_game: decimal.Decimal
    free_throws_attempted_per_game: decimal.Decimal


class WnbaSeason(msgspec.Struct):
    id: int
    season_year: str


class WnbaTeam(msgspec.Struct):
    id: int
    name: str
    team_city: str
    team_abv: str
    conference: str
    ppg: float
    oppg: float
    wins: int
    loss: int
    team_bpg: float
    team_spg: float
    team_apg: float
    team_fga: float
    team_fgm: float
    team_fta: float
    team_tov: float
