-- name: MlbTeamsUpsert :exec
INSERT INTO mlb_teams (
    team_abv,
    team_city,
    team_name,
    conference,
    division,
    rs,
    ra,
    wins,
    losses,
    run_diff
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (team_abv) DO UPDATE SET
    team_city = excluded.team_city,
    team_name = excluded.team_name,
    conference = excluded.conference,
    division = excluded.division,
    rs = excluded.rs,
    ra = excluded.ra,
    wins = excluded.wins,
    losses = excluded.losses,
    run_diff = excluded.run_diff;


-- name: MlbPlayersUpsert :exec
INSERT INTO mlb_players (
    player_id,
    long_name,
    team_abv,
    pos,
    height,
    weight,
    bat,
    throw,
    b_day,
    mlb_headshot,
    espn_headshot,
    espn_status,
    injury_description,
    injury_return
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (player_id) DO UPDATE SET
    long_name = excluded.long_name,
    team_abv = excluded.team_abv,
    pos = excluded.pos,
    height = excluded.height,
    weight = excluded.weight,
    bat = excluded.bat,
    throw = excluded.throw,
    b_day = excluded.b_day,
    mlb_headshot = excluded.mlb_headshot,
    espn_headshot = excluded.espn_headshot,
    espn_status = excluded.espn_status,
    injury_description = excluded.injury_description,
    injury_return = excluded.injury_return;


-- name: MlbPlayerGameStatsUpsert :exec
INSERT INTO mlb_player_game_stats (
    player_id,
    game_id,
    team,
    started,
    starting_position,
    all_positions_played,
    bb,
    ab,
    h,
    hr,
    rbi,
    so,
    avg,
    tb,
    doubles,
    triples,
    r,
    ibb,
    sf,
    sac,
    hbp,
    gidp,
    p_bb,
    p_h,
    p_hr,
    p_er,
    p_so,
    win,
    loss,
    save,
    era,
    innings_pitched,
    fielding_e,
    passed_ball,
    of_assists,
    pickoffs,
    sb,
    cs,
    po
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38,
    $39
)
ON CONFLICT (player_id, game_id) DO NOTHING;
