"""WC 2026 team name -> FotMob playerInformation countryCode hints."""

from __future__ import annotations

# Values observed in live playerData.playerInformation[].countryCode
TEAM_COUNTRY_CODES: dict[str, frozenset[str]] = {
    "Mexico": frozenset({"MEX"}),
    "South Africa": frozenset({"RSA", "ZAF"}),
    "South Korea": frozenset({"KOR", "KOR"}),
    "Czechia": frozenset({"CZE", "CZE"}),
    "Canada": frozenset({"CAN"}),
    "Bosnia and Herzegovina": frozenset({"BIH"}),
    "Qatar": frozenset({"QAT"}),
    "Switzerland": frozenset({"SUI"}),
    "Brazil": frozenset({"BRA"}),
    "Morocco": frozenset({"MAR"}),
    "Haiti": frozenset({"HAI"}),
    "Scotland": frozenset({"SCO"}),
    "United States": frozenset({"USA"}),
    "Paraguay": frozenset({"PAR"}),
    "Australia": frozenset({"AUS"}),
    "Turkiye": frozenset({"TUR"}),
    "Germany": frozenset({"GER"}),
    "Curacao": frozenset({"CUW", "CUW"}),
    "Ivory Coast": frozenset({"CIV", "CIV"}),
    "Ecuador": frozenset({"ECU"}),
    "Netherlands": frozenset({"NED"}),
    "Japan": frozenset({"JPN"}),
    "Sweden": frozenset({"SWE"}),
    "Tunisia": frozenset({"TUN"}),
    "Belgium": frozenset({"BEL"}),
    "Egypt": frozenset({"EGY"}),
    "Iran": frozenset({"IRN"}),
    "New Zealand": frozenset({"NZL"}),
    "Spain": frozenset({"ESP"}),
    "Cape Verde": frozenset({"CPV"}),
    "Saudi Arabia": frozenset({"KSA", "SAU"}),
    "Uruguay": frozenset({"URU"}),
    "France": frozenset({"FRA"}),
    "Senegal": frozenset({"SEN"}),
    "Iraq": frozenset({"IRQ"}),
    "Norway": frozenset({"NOR"}),
    "Argentina": frozenset({"ARG"}),
    "Algeria": frozenset({"ALG", "DZA"}),
    "Austria": frozenset({"AUT"}),
    "Jordan": frozenset({"JOR"}),
    "Portugal": frozenset({"POR"}),
    "DR Congo": frozenset({"COD", "CDR", "COD"}),
    "Uzbekistan": frozenset({"UZB"}),
    "Colombia": frozenset({"COL"}),
    "England": frozenset({"ENG"}),
    "Croatia": frozenset({"CRO"}),
    "Ghana": frozenset({"GHA"}),
    "Panama": frozenset({"PAN"}),
}

# Alternate spellings to try when primary search returns nothing.
SEARCH_ALIASES: dict[str, list[str]] = {
    "Son Heung-min": ["Heung-min Son", "Son Heung Min"],
    "Vinicius Jr": ["Vinicius Junior", "Vinícius Júnior"],
    "Neymar": ["Neymar Jr"],
    "Türkiye": [],
    "Ivory Coast": ["Cote d'Ivoire"],
    "DR Congo": ["Congo DR", "Democratic Republic of the Congo"],
    "Cape Verde": ["Cabo Verde"],
    "Curacao": ["Curaçao"],
    "Trezeguet": ["Mahmoud Hassan"],
    "Mohamed Kanno": ["Mohammed Kanno"],
    "Jean-Ricner Bellegarde": ["Bellegarde"],
    "Derrick Etienne Jr.": ["Derrick Etienne"],
    "Gustavo Gomez": ["Gustavo Gómez"],
    "Moises Caicedo": ["Moisés Caicedo"],
    "Willian Pacho": ["Pacho"],
    "Takefusa Kubo": ["Kubo"],
    "Viktor Gyokeres": ["Viktor Gyökeres", "Gyokeres"],
    "Omar Marmoush": ["Marmoush"],
    "Lamine Yamal": ["Yamal"],
    "Salem Al-Dawsari": ["Al-Dawsari"],
    "Michael Olise": ["Olise"],
    "Nicolas Jackson": ["Jackson"],
    "Zidane Iqbal": ["Iqbal"],
    "Riyad Mahrez": ["Mahrez"],
    "Mohamed Amoura": ["Amoura"],
    "David Alaba": ["Alaba"],
    "Mousa Al-Tamari": ["Mousa Tamari", "Al-Tamari"],
    "Cristiano Ronaldo": ["Ronaldo"],
    "Yoane Wissa": ["Wissa"],
    "Aaron Wan-Bissaka": ["Wan-Bissaka"],
    "Abdukodir Khusanov": ["Khusanov"],
    "Eldor Shomurodov": ["Shomurodov"],
    "Luis Diaz": ["Luis Díaz"],
    "James Rodriguez": ["James Rodríguez"],
    "Luka Modric": ["Luka Modrić"],
    "Josko Gvardiol": ["Gvardiol"],
    "Inaki Williams": ["Iñaki Williams"],
    "Adalberto Carrasquilla": ["Carrasquilla"],
    "Edin Dzeko": ["Edin Džeko"],
    "Granit Xhaka": ["Xhaka"],
    "Achraf Hakimi": ["Hakimi"],
    "Brahim Diaz": ["Brahim Díaz"],
    "Arda Guler": ["Arda Güler"],
    "Hakan Calhanoglu": ["Hakan Çalhanoğlu"],
    "Kenan Yildiz": ["Kenan Yıldız"],
    "Florian Wirtz": ["Wirtz"],
    "Jeremy Doku": ["Jérémy Doku"],
    "Mehdi Taremi": ["Taremi"],
    "Alireza Jahanbakhsh": ["Jahanbakhsh"],
    "Chris Wood": ["Wood"],
    "Federico Valverde": ["Valverde"],
    "Darwin Nunez": ["Darwin Núñez"],
    "Kylian Mbappe": ["Kylian Mbappé", "Mbappe"],
    "Ousmane Dembele": ["Ousmane Dembélé"],
    "Sadio Mane": ["Sadio Mané"],
    "Lautaro Martinez": ["Lautaro Martínez"],
    "Julian Alvarez": ["Julián Álvarez"],
    "Amine Gouiri": ["Gouiri"],
    "Konrad Laimer": ["Laimer"],
    "Bruno Fernandes": ["Fernandes"],
    "Richard Rios": ["Ríos"],
    "Antoine Semenyo": ["Semenyo"],
    "Thomas Partey": ["Partey"],
    "Patrik Schick": ["Schick"],
    "Tomas Soucek": ["Tomáš Souček"],
    "Alphonso Davies": ["Davies"],
    "Jonathan David": ["David"],
    "Christian Pulisic": ["Pulisic"],
    "Miguel Almiron": ["Miguel Almirón"],
    "Julio Enciso": ["Enciso"],
    "Mathew Ryan": ["Ryan"],
    "Virgil van Dijk": ["van Dijk"],
    "Frenkie de Jong": ["de Jong"],
    "Cody Gakpo": ["Gakpo"],
    "Kevin De Bruyne": ["De Bruyne"],
    "Romelu Lukaku": ["Lukaku"],
    "Rodri": ["Rodrigo"],
    "Pedri": ["Pedri"],
    "Ronald Araujo": ["Ronald Araújo"],
    "Martin Odegaard": ["Martin Ødegaard"],
    "Mateo Kovacic": ["Mateo Kovačić"],
    "Hannibal Mejbri": ["Mejbri"],
    "Ellyes Skhiri": ["Skhiri"],
    "Gilberto Mora": ["Mora"],
    "Raul Jimenez": ["Raúl Jiménez"],
    "Ronwen Williams": ["Williams"],
    "Lyle Foster": ["Foster"],
    "Kim Min-jae": ["Kim Min Jae", "Min-jae Kim"],
    "Lee Kang-in": ["Kang-in Lee"],
    "Ermedin Demirovic": ["Demirović"],
    "Akram Afif": ["Afif"],
    "Almoez Ali": ["Ali"],
    "Manuel Akanji": ["Akanji"],
    "Dan Ndoye": ["Ndoye"],
    "Raphinha": ["Raphinha"],
    "Yassine Bounou": ["Bounou"],
    "Wilson Isidor": ["Isidor"],
    "Scott McTominay": ["McTominay"],
    "Andy Robertson": ["Robertson"],
    "John McGinn": ["McGinn"],
    "Weston McKennie": ["McKennie"],
    "Folarin Balogun": ["Balogun"],
    "Jackson Irvine": ["Irvine"],
    "Nestory Irankunda": ["Irankunda"],
    "Jamal Musiala": ["Musiala"],
    "Joshua Kimmich": ["Kimmich"],
    "Tahith Chong": ["Chong"],
    "Riechedly Bazoer": ["Bazoer"],
    "Juninho Bacuna": ["Bacuna"],
    "Amad Diallo": ["Diallo"],
    "Franck Kessie": ["Kessie"],
    "Yan Diomande": ["Diomande"],
    "Piero Hincapie": ["Hincapié"],
    "Alexander Isak": ["Isak"],
    "Anthony Elanga": ["Elanga"],
    "Montassar Talbi": ["Talbi"],
    "Saman Ghoddos": ["Ghoddos"],
    "Marko Stamenic": ["Stamenic"],
    "Liberato Cacace": ["Cacace"],
    "Ryan Mendes": ["Mendes"],
    "Logan Costa": ["Costa"],
    "Garry Rodrigues": ["Rodrigues"],
    "Feras Al-Brikan": ["Al-Brikan"],
    "Ismaila Sarr": ["Sarr"],
    "Aymen Hussein": ["Hussein"],
    "Ali Al-Hamadi": ["Al-Hamadi"],
    "Alexander Sorloth": ["Sørloth"],
    "Marcel Sabitzer": ["Sabitzer"],
    "Ali Olwan": ["Olwan"],
    "Nizar Al-Rashdan": ["Al-Rashdan"],
    "Chancel Mbemba": ["Mbemba"],
    "Abbosbek Fayzullaev": ["Fayzullaev"],
    "Harry Kane": ["Kane"],
    "Bukayo Saka": ["Saka"],
    "Jude Bellingham": ["Bellingham"],
    "Cecilio Waterman": ["Waterman"],
    "Ismael Diaz": ["Díaz"],
    "Edson Alvarez": ["Alvarez"],
    "Teboho Mokoena": ["Mokoena"],
    "Adam Hlozek": ["Hlozek"],
    "Stephen Eustaquio": ["Eustaquio"],
    "Amar Dedic": ["Dedic"],
    "Hassan Al Haydos": ["Al Haydos"],
    "Vitinha": ["Vitinha"],
}


def player_country_code(player_data: dict) -> str | None:
    for block in player_data.get("playerInformation") or []:
        if block.get("title") == "Country":
            code = block.get("countryCode")
            if code:
                return str(code).upper()
            icon = block.get("icon") or {}
            if icon.get("id"):
                return str(icon["id"]).upper()
    return None


def country_matches_team(team: str, country_code: str | None) -> bool:
    if not country_code:
        return False
    expected = TEAM_COUNTRY_CODES.get(team)
    if not expected:
        return False
    return country_code.upper() in {c.upper() for c in expected}
