name: Daily Script Run

on:
  schedule:
    - cron: '5 0 * * *'  # Runs daily at 1 AM PST (9 AM UTC) 0 9 * * * is 1 am 
    # 4:05 pm pst is 

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary requests

      - name: Run Daily Task
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          python daily_colab_task/daily_task.py
