name: Daily Bets Analysis

on:
  schedule:
    # 1 AM Pacific / 13 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sport: [mlb, wnba]
    name: ${{ matrix.sport }}-analysis
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Analysis
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}

          MLB_API_KEY: ${{ secrets.MLB_API_KEY }}
          MLB_API_HOST: ${{ secrets.MLB_API_HOST }}

          WNBA_API_KEY: ${{ secrets.WNBA_API_KEY }}
          WNBA_API_HOST: ${{ secrets.WNBA_API_HOST }}
        run: uv run -m db_update ${{ matrix.sport }}