name: Daily MLB Database Update

on:
  schedule:
    # Runs everyday at 10:30 AM UTC  (≈ 3:30 AM PST) – adjust as you like
    - cron:  '30 10 * * *'
  workflow_dispatch:

jobs:
  mlb-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary requests

      - name: Run MLB updater
        env:
          DB_NAME:      ${{ secrets.DB_NAME }}
          DB_USER:      ${{ secrets.DB_USER }}
          DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}
          DB_HOST:      ${{ secrets.DB_HOST }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
        run: |
          python mlb-update.py
