name: Update MLB Probable Pitchers

on:
  schedule:
    # 1 AM Pacific is 09:00 UTC
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update-pitchers:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary beautifulsoup4 pandas numpy requests

      - name: Run probable pitchers update
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          python probable_pitchers/update_probable_pitchers.py
